### ISSUE TITLE
Frontend Intern Assignment - Consume RestAPI and Show Recipe Details

### ISSUE THREAD

**Issue by amanintech** [amanintech/dinnerfy-fe#1]
## Your Mission if you choose to accept 😎
You are agent Dinnerfy whose job is to find the best dinner ideas for our super-hungry users. Our backend engineer has already setup a Rest API but he forgot to build the UI. That's where we need you 

## Tasks 

- [ ] Clone this repository and deploy it on vercel 
- [ ] Consume the Rest endpoint here - https://dinnerfy-ds-production.up.railway.app/recipe. This takes the following body and returns the recipe details. 
`{
"RecipeID": 60,
"Servings": 3
}`
- [ ] Develop a frontend that takes Recipe ID and Number of serving and displays the respective recipe beautifully
- [ ] Extra points for best UI drops ( Refer to dinnerfy.com for design ideas )
- [ ] Once you have done this. Create a pull request with this repo which should create a preview links from vercel. 

Reach out at Wellfound if you are stuck, or ask in comments.

**Comment by SauravKumar-max** [comment]
Hey Aman,

The API currently doesn't have a CORS policy in place. As a result, I'm getting a CORS error when attempting to fetch the API in my Next.js project.

Would it be possible to solve this issue on the frontend, or is it something that can only be resolved from your end?

![cors_error](https://github.com/amanintech/dinnerfy-fe/assets/56781693/50bffa2e-ff02-42a4-89ec-087d9a94adef)

**Comment by Aps2612** [comment]
I am facing the same issue of CORS error while fetching API.Also tried with chrome extension "Allow CORS: Access-Control-Allow-Origin"  but still not able to get the data.
I also do have same question whether would it be possible to solve this on the frontend, or is it something that can only be resolved from your end?
![Screenshot (412)](https://github.com/amanintech/dinnerfy-fe/assets/91000024/5f44f70b-6419-4954-b53b-fc792756a227)

**Comment by tushar0907** [comment]
I didn't got any problems sir please check my project i have made a pull request!

**Comment by mazam5** [comment]
I have deployed using vercel.
visit link: https://dinner-app-nextjs-irtncccsv-mohammedazam55.vercel.app/
however I don't know, how to configure the python server.

**Comment by 8rxn** [comment]
Done with a [solution](https://github.com/amanintech/dinnerfy-fe/pull/6) that works. Hoping for a positive response.

**Comment by NV404** [comment]
I finished my [assignments](https://dinnerfy-fe-git-fork-nv404-main-amanintech.vercel.app) and submitted a pull request. I'm hoping for a favorable reaction.
Preview Link: [https://dinnerfy-fe-git-fork-nv404-main-amanintech.vercel.app/](https://dinnerfy-fe-git-fork-nv404-main-amanintech.vercel.app/)
